easy_admin:
    edit:
        actions: ['-delete']
    list:
        actions: ['edit', 'search', '-delete']
    show:
        actions: ['-delete', '-list']
    formats:
        number: '%.8f'
    entities:
         User:
            disabled_actions: ['new']
            show:
                title: 'User'
                actions:
                    - { name: 'edit', icon: 'pencil', label: 'Edit', title: 'Edit' }
            list:
                fields: ['id', 'email', 'enabled', 'balance', 'roles']
                title: 'Bitcoin Wallet Users'
                actions:
                    - { name: 'show', icon: 'user', label: 'Show', title: 'Show' }
                    - { name: 'edit', icon: 'pencil', label: 'Edit', title: 'Edit' }
            edit:
                title: Edit User
                actions:
                    - { name: 'list', icon: 'list', label: 'List', title: 'List' }
 
            class: App\Entity\User
            form:
                fields:
                    - email
                    - password
                    - enabled
                    - balance
                    - roles
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category

    site_name: 'Bitcoin Wallet'
    #prefix:   /_secret_backend  # <-- change this value
    design:
        brand_color: '#2196F3'
