security:
    encoders:
        FOS\UserBundle\Model\UserInterface: argon2i #requires PHP 7.2 or libsodium

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            pattern:    ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            remember_me:
                secret: '%kernel.secret%'
            logout:
                path: /logout
                target: /login

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
         - { path: ^/wallet, roles: [ROLE_USER, ROLE_ADMIN, ROLE_SUPER_ADMIN] }
         - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/admin, role: [ROLE_SUPER_ADMIN] }
